### ISSUE TITLE
Language Ukraine

### ISSUE THREAD

**Issue by MusienkoAnton** [IvanVSmirnov/dokuwiki-tgnotify#1]
I`ve add lang and add variant to send size of doc
[tgnotify.zip](https://github.com/IvanVSmirnov/dokuwiki-tgnotify/files/13761863/tgnotify.zip)

**Comment by IvanVSmirnov** [comment]
Anton, thank you for translation!
I doubt it a little bit about language code. As I understand Ukrainian language code, according ISO 3166-1 is "UA" - not a "UK".  Maybe I'm wrong. Have you tested this pull request? Is it working?

**Comment by IvanVSmirnov** [comment]
Accepted in v1.0.9
